-- ==============================================
-- ShopEase Mini E-Commerce Database
-- Compatible with MySQL 8.x (Laragon 6)
-- ==============================================

CREATE DATABASE IF NOT EXISTS `shopease` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `shopease`;

-- -----------------------------------------------
-- Table: users
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name`       VARCHAR(100) NOT NULL,
  `email`      VARCHAR(150) NOT NULL UNIQUE,
  `password`   VARCHAR(255) NOT NULL,
  `phone`      VARCHAR(20)  DEFAULT NULL,
  `gender`     ENUM('male','female','other') DEFAULT NULL,
  `birth_date` DATE         DEFAULT NULL,
  `role`       ENUM('user','admin') NOT NULL DEFAULT 'user',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

-- -----------------------------------------------
-- Table: categories
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS `categories` (
  `id`        INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name`      VARCHAR(100) NOT NULL,
  `icon`      VARCHAR(50)  DEFAULT 'category',
  `is_active` TINYINT(1)   NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

-- -----------------------------------------------
-- Table: products
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS `products` (
  `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` INT UNSIGNED NOT NULL,
  `name`        VARCHAR(200) NOT NULL,
  `description` TEXT         DEFAULT NULL,
  `image_url`   TEXT         DEFAULT NULL,
  `price`       DECIMAL(15,2) NOT NULL DEFAULT 0,
  `stock`       INT          NOT NULL DEFAULT 0,
  `rating`      DECIMAL(3,1) NOT NULL DEFAULT 0,
  `created_at`  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- -----------------------------------------------
-- Table: cart_items
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS `cart_items` (
  `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id`    INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `quantity`   INT          NOT NULL DEFAULT 1,
  `added_at`   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_product` (`user_id`, `product_id`),
  FOREIGN KEY (`user_id`)    REFERENCES `users`(`id`)    ON DELETE CASCADE,
  FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- -----------------------------------------------
-- Table: transactions
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS `transactions` (
  `id`                 INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  `user_id`            INT UNSIGNED  NOT NULL,
  `grand_total`        DECIMAL(15,2) NOT NULL,
  `recipient_name`     VARCHAR(100)  DEFAULT NULL,
  `phone`              VARCHAR(20)   DEFAULT NULL,
  `address`            TEXT          DEFAULT NULL,
  `payment_method`     VARCHAR(50)   DEFAULT 'transfer',
  `status`             ENUM('pending','processing','delivered','completed','cancelled') NOT NULL DEFAULT 'pending',
  `midtrans_order_id`  VARCHAR(100)  DEFAULT NULL,
  `snap_token`         TEXT          DEFAULT NULL,
  `paid_at`            TIMESTAMP     NULL DEFAULT NULL,
  `created_at`         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- -----------------------------------------------
-- Table: transaction_details
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS `transaction_details` (
  `id`                 INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `transaction_id`     INT UNSIGNED NOT NULL,
  `product_id`         INT UNSIGNED NOT NULL,
  `quantity`           INT          NOT NULL DEFAULT 1,
  `price_at_purchase`  DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`transaction_id`) REFERENCES `transactions`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`product_id`)     REFERENCES `products`(`id`)     ON DELETE RESTRICT
) ENGINE=InnoDB;

-- ==============================================
-- SEED DATA
-- ==============================================

-- Admin user (password: admin123)
-- Hash generated by: password_hash('admin123', PASSWORD_BCRYPT)
INSERT INTO `users` (`name`, `email`, `password`, `role`) VALUES
('Budi Santoso', 'admin@shopease.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin');

-- Demo user (password: user123)  
-- Hash generated by: password_hash('user123', PASSWORD_BCRYPT)
INSERT INTO `users` (`name`, `email`, `password`, `phone`, `gender`, `role`) VALUES
('John Doe', 'user@shopease.com', '$2y$10$TKh8H1.PfbuJ7WR1cjzZBOQSWBmWpgczHt5T0UgEGqj1mDEQ7GFC.', '082234567890', 'male', 'user');

-- Categories
INSERT INTO `categories` (`name`, `icon`) VALUES
('Elektronik', 'smartphone'),
('Fashion', 'checkroom'),
('Makanan', 'restaurant'),
('Olahraga', 'sports_soccer'),
('Aksesoris', 'watch');

-- Products
INSERT INTO `products` (`category_id`, `name`, `description`, `image_url`, `price`, `stock`, `rating`) VALUES
(1, 'Wireless Headphones', 'Headphone nirkabel premium dengan suara hi-fi dan noise cancelling terdepan.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBrC53F3qvqukI30pb2WXnJ70rKfp5AnIMXDiypvFXOPY-jBMX7gbJw7aBxTJqMODsNxz9olecDD8FAFqzOt3ycvxRBrmgW4AJBHf7irvowTxn1Xcuwk1dEtRksT4I8BnQwhyEP23Kit_BNcpum-_TsKu0jnBrLGC5ppwtGrR0mEHH7vVjUiaCgQtst5NEqw07TVjAbrzPkVF6IyWlYyfwd58o1Rca3Ghkvpth5PKe4ehG7zDsYsvHAp_XFI6PKxQvOgNphMkLytw10', 750000, 12, 4.8),
(5, 'Smart Watch Pro',     'Jam tangan pintar dengan monitor kesehatan, GPS, dan layar AMOLED terang.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBOJ2Db17THrP1NiwFI6Zq5rF4PcL3iR6MjkVMD4jSMoZQs_W4A10fWZRwWd9QCdi1ePDV21iXp7969H9UPf8QR4HBx-y2YRoppPoncYXOAprxtq2Dwb5eezw5okEM_PTOA8zYc9U_fjhn4skJpu13jSv7JF2CyzzwhwDP8kbNTe7zbrmPjvWLKYDjQb1S06P_sHzLY5KdiTwr8JEa_pU1WEY_KGQy4nfBd7jYNJpwHB8rJs0M1q2hAN9_4gNtdVkI53aIvaZ0r0FeK', 1200000, 5,  4.9),
(2, 'Leather Wallet',      'Dompet kulit asli berkualitas tinggi dengan banyak slot kartu.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuDxWVR-I9uKs_PHsK2hSex0h1Z5zE1_hbfSqYdhrLggVtM_8wvvrWzLibb6klumb9PkJ4DDiPyeepSEjXfpceDpJRe0YJs0jX4t22wm79keOyT5GYgDM7laAmW4ZRN3MAr04GhCERrYI455D6s9vKoCLEIcO9_YW_zM6fjz4zBzBsYRdNvIUvirsB0tS0hdClaYmIW_jnXx6QqwpyGdiDrDfu5FtQZOB13r4rihj111x1yakSejaVBHqQXDn2urmBKIzQm_c_uUxFzA', 350000,  20, 4.7),
(4, 'Swift Running Shoes', 'Sepatu lari ringan dengan teknologi bantalan udara untuk performa maksimal.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuD46g9osrXjqqVtuUjbcKDiwEOXIkgR_UFF8Z7BYJHboADGZUUENoVYUBP9T2kg4c6Cn1j8aTJ5fJHMOMDRrRGbY7UBnmWE9VUir4riE9nH7jSgciBYfcUP8zEs8JoB_VCk2OQAukpqY6T-fbdNe2q_KbztZcxCxEJkwZwkfeVe90q1oYwdC-1ErwRtiHiN7Xadldjvv2NQb_8yDbUU27FARasd_5MCA3hykwK88AG2V92c8ZdisznhQczMm1eiP-DBV0C2BLYX4bDR', 890000,  8,  4.6),
(1, 'Mechanical Keyboard', 'Keyboard mekanikal dengan switch tactile tahan lama untuk produktivitas.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuC6CacI5q1KYj0dB20KIPx4uarNKDLA6EufB_5qdzAXHiBi-DloRsutPD_TqEgJSSl5xWDSKoW2btOfRIxfXIKkyg8PXraBOsQ50_lx3qZSqTVzIN4H-HFVHZLkbBIQuncH5Y-H-Kx-5vQmDK7j4X8rWC-NHF1CAS63uUTpsKPtcou5IxaDTxOPHgdrOXdbwQLQjQHXqsvv8pIB7hpX4QT_TqbXhCrN-7DHao28yTu5v-qcXLKv6sgB-72Whd_IMrXx3xph-xVJ7SyI', 450000,  15, 4.5),
(2, 'Sport Jersey',        'Jersey olahraga ringan, menyerap keringat, cocok untuk aktivitas outdoor.', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBHK8KCuQnDBZksBZ-MvbNmtdCfY1S5Mebnfwno9aOZnyuHj7JQsPPYrY8DZcvu-_DG_WwCiDWb3fcav-7epGkz57QA-Za-LZ8hoTh8HwsejoVH-p3IPMYW0N6QPlkdcLWzHh2kiSYVUOkAagbJzQn5Zma1NuQftPh93et__dI0JAq4cTkXb3_zA_ZBFEtqzpxIjEOQtztsrTxU8d8Yd5ym6Khb0mL5JCbO-DZICWBW_NsxJ2f-Z3EfmAq9yMs_gemuTFiq39WcirmH', 220000,  30, 4.3);

-- ==============================================
-- MIGRATION: Tambah kolom Midtrans ke transactions
-- Jalankan hanya jika database sudah ada sebelumnya
-- ==============================================
ALTER TABLE `transactions`
    ADD COLUMN IF NOT EXISTS `midtrans_order_id` VARCHAR(100) DEFAULT NULL AFTER `status`,
    ADD COLUMN IF NOT EXISTS `snap_token`        TEXT         DEFAULT NULL AFTER `midtrans_order_id`,
    ADD COLUMN IF NOT EXISTS `paid_at`           TIMESTAMP    NULL DEFAULT NULL AFTER `snap_token`;

